### ISSUE TITLE
bing chat enterprise

### ISSUE THREAD

**Issue by Rainson12** [patrik-martinko/app-bing-ai-for-chrome#1]
Hi,
it seems that this extension doesnt work:
![image](https://github.com/patrik-martinko/app-bing-ai-for-chrome/assets/13119203/815f5dcc-c406-492c-b060-b4b12ef6f0a1)

vs edge:
![image](https://github.com/patrik-martinko/app-bing-ai-for-chrome/assets/13119203/42c05bc2-966c-46c8-ad2e-b23608d2adb0)

**Comment by patrik-martinko** [comment]
Hi. You need to click "Chat beginnen" to start Bing AI and close the welcome banner by Microsoft.

![255189587-815f5dcc-c406-492c-b060-b4b12ef6f0a1](https://github.com/patrik-martinko/app-bing-ai-for-chrome/assets/12855743/65b8a890-002a-4d7b-b28f-d4030ce8c8ff)

**Comment by Rainson12** [comment]
I tried that but it wouldn't accept the business account while when doing the exact same with edge it works perfectly fine.

**Comment by patrik-martinko** [comment]
What does it mean "wouldn't accept the business account"? What happens when you click "Chat beginnen"?

Also try to disable all other browser extensions because many extensions (VPNs, ad blockers, cookies, ...) break the Bing AI functionality and keep the welcome banner stucked.

But the extension seems to work for you because the website shows you the welcome banner instead of the "Open in Microsoft Edge" banner:

![image](https://github.com/patrik-martinko/app-bing-ai-for-chrome/assets/12855743/1917a8c0-9bd7-427e-bc83-756ecc682751)
