### ISSUE TITLE
Signin not applied to chat.

### ISSUE THREAD

**Issue by parsanoori** [patrik-martinko/app-bing-ai-for-chrome#5]
I've signed in to bing but the conversations are limited to 10 messages and on the chat page I get:

>  Sign in to ask more questions and have longer conversations

The photo is provided.

<img width="1506" alt="Screenshot 1402-10-11 at 11 17 25 PM" src="https://github.com/patrik-martinko/app-bing-ai-for-chrome/assets/40103436/ca5ad6c1-39b0-496d-92aa-a6ca23b00c08">

I'm on brave version of this extension and I'd be glad to help if possible.

**Comment by patrik-martinko** [comment]
Hi. This extension doesn't change or intercept functionality of Bing AI, only sets a HTTP header, so it cannot beak the functionality. Bing AI itself is often faulty (because MS updates the Bing AI often), especially on Brave because it blocks some scripts. You can try disable the Brave shield (It helped me multiple times when something didn't work on Bing AI).

**Comment by parsanoori** [comment]
You are write the problems was the cross-site cookie blocking.
Thank you for your help.
